[package]
name = "coin-sample"
version = "0.1.0"

[addresses]
coin_address = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
